sonar.projectKey=flask_image_recognition
sonar.projectName=Flask Image Recognition
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
# sonar.exclusions=venv/**,**/*.pyc,tests/**  # adjust if needed
# If you produce pytest coverage, uncomment and set path:
# sonar.python.coverage.reportPaths=coverage.xml